// maps/catalog.js
// Catalog definitions for FPS Elemental Items & PBR Filament Materials

export const ELEMENTAL_ITEMS_CATALOG = {
  health_small: { key: "health_small", name: "Small Health Vial", category: "health", icon: "❤️", color: [0.15, 0.95, 0.65], typePill: "Health +15", effect: "+15 HP", desc: "Instantly restores 15 Health points up to base capacity (100 HP).", respawnDelay: 15.0, meshType: "sphere", scale: [0.35, 0.35, 0.35], sound: "health" },
  health_medium: { key: "health_medium", name: "Medium Health Pack", category: "health", icon: "💚", color: [0.10, 0.85, 0.40], typePill: "Health +25", effect: "+25 HP", desc: "Field surgical combat kit restoring 25 Health points up to 100 HP.", respawnDelay: 20.0, meshType: "sphere", scale: [0.45, 0.45, 0.45], sound: "health" },
  megahealth: { key: "megahealth", name: "MegaHealth Sphere", category: "health", icon: "💎", color: [0.06, 0.92, 0.95], typePill: "Overheal +100", effect: "+100 HP Overheal (Max 200 HP)", desc: "Pulsing bio-energy core boosting maximum health beyond limit up to 200 HP.", respawnDelay: 60.0, meshType: "sphere", scale: [0.55, 0.55, 0.55], sound: "health_mega" },

  armor_green: { key: "armor_green", name: "Green Combat Armor", category: "armor", icon: "🛡️", color: [0.10, 0.85, 0.45], typePill: "Armor +50", effect: "+50 AP (50% Absorb)", desc: "Light Kevlar weave vest absorbing 50% of incoming kinetic damage.", respawnDelay: 25.0, meshType: "cube", scale: [0.50, 0.50, 0.50], sound: "armor" },
  armor_yellow: { key: "armor_yellow", name: "Yellow Combat Armor", category: "armor", icon: "🛡️", color: [0.95, 0.80, 0.15], typePill: "Armor +75", effect: "+75 AP (66% Absorb)", desc: "Medium ceramic composite battle plate absorbing 66% of damage.", respawnDelay: 25.0, meshType: "cube", scale: [0.55, 0.55, 0.55], sound: "armor" },
  armor_red: { key: "armor_red", name: "Red Heavy Battle Armor", category: "armor", icon: "🛡️", color: [0.95, 0.20, 0.30], typePill: "Armor +100", effect: "+100 AP (75% Absorb)", desc: "Heavy powered titanium exoskeleton providing 75% damage mitigation.", respawnDelay: 30.0, meshType: "cube", scale: [0.60, 0.60, 0.60], sound: "armor_heavy" },

  ammo_plasma: { key: "ammo_plasma", name: "Plasma Energy Cells", category: "ammo", icon: "⚡", color: [0.06, 0.85, 0.95], typePill: "Energy +50", effect: "+50 Energy Cells", desc: "Superheated ionized plasma canister for plasma bolt rifles.", respawnDelay: 20.0, meshType: "cube", scale: [0.45, 0.45, 0.45], sound: "ammo" },
  ammo_slugs: { key: "ammo_slugs", name: "Heavy Kinetic Slugs", category: "ammo", icon: "💥", color: [0.95, 0.65, 0.15], typePill: "Ammo +30", effect: "+30 Kinetic Slugs", desc: "Depleted uranium high-density slugs for rapid-fire ballistic cannons.", respawnDelay: 20.0, meshType: "cube", scale: [0.45, 0.45, 0.45], sound: "ammo" },
  ammo_rockets: { key: "ammo_rockets", name: "HE Rocket Shells", category: "ammo", icon: "🚀", color: [0.95, 0.45, 0.10], typePill: "Rockets +10", effect: "+10 HE Rockets", desc: "High-explosive rocket ordnance pods with blast radius capability.", respawnDelay: 25.0, meshType: "cube", scale: [0.50, 0.50, 0.50], sound: "ammo" },
  ammo_railgun: { key: "ammo_railgun", name: "Quantum Railgun Slugs", category: "ammo", icon: "🔮", color: [0.85, 0.35, 0.95], typePill: "Railgun +15", effect: "+15 Pulse Slugs", desc: "Quantum accelerated relativistic projectile slugs for sniper railguns.", respawnDelay: 30.0, meshType: "gem", scale: [0.50, 0.50, 0.50], sound: "ammo" },

  powerup_quad: { key: "powerup_quad", name: "Quad Damage Rune", category: "powerup", icon: "⚡", color: [0.20, 0.55, 1.0], typePill: "Powerup (4x DMG)", effect: "4.0x Damage Multiplier (30s)", desc: "Legendary Quake rune amplifying all weapon projectile damage by 400%.", respawnDelay: 120.0, meshType: "gem", scale: [0.65, 0.65, 0.65], sound: "powerup" },
  powerup_haste: { key: "powerup_haste", name: "Haste Speed Rune", category: "powerup", icon: "🏃", color: [0.95, 0.85, 0.15], typePill: "Powerup (+60% Spd)", effect: "+60% Move & Sprint Speed (25s)", desc: "Hyper-kinetic rune accelerating locomotion, sprint, and jump velocity.", respawnDelay: 90.0, meshType: "gem", scale: [0.65, 0.65, 0.65], sound: "powerup" },
  powerup_regen: { key: "powerup_regen", name: "Regeneration Rune", category: "powerup", icon: "💚", color: [0.15, 0.95, 0.45], typePill: "Powerup (+15 HP/s)", effect: "+15 HP/sec Regen (30s)", desc: "Continuous cellular nanite repair restoring 15 Health per second.", respawnDelay: 90.0, meshType: "gem", scale: [0.65, 0.65, 0.65], sound: "powerup" }
};

export const FILAMENT_MATERIALS_CATALOG = {
  wood: {
    key: "wood",
    name: "Procedural Dark Walnut Wood",
    category: "procedural",
    icon: "🌲",
    matTypeId: 1,
    bumpStrength: 1.6,
    color: [0.38, 0.22, 0.12],
    roughness: 0.48,
    metallic: 0.0,
    clearCoat: 0.05,
    noiseScale: 22.0,
    anisotropy: 0.15,
    textureKey: "wood",
    textureUrl: "/assets/textures/wal1.webp",
    proceduralType: "wood",
    swatch: "linear-gradient(135deg, #5c3a21 0%, #2b180d 100%)",
    desc: "Procedural wood grain synthesis using sine-wave ring perturbations, fine grain lines, and 2D bark texture sampler.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "16 ALUs",
      texSamplers: "1 Albedo Map (wal1.webp)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Ultra Safe for Mobile",
      desc: "Combined 2D texture sampler and procedural wood grain synthesis."
    }
  },
  rock: {
    key: "rock",
    name: "Procedural Basalt & Granite Rock",
    category: "procedural",
    icon: "🗿",
    matTypeId: 2,
    bumpStrength: 2.5,
    color: [0.32, 0.32, 0.35],
    roughness: 0.88,
    metallic: 0.0,
    clearCoat: 0.0,
    noiseScale: 14.0,
    anisotropy: 0.0,
    textureKey: "rust",
    textureUrl: "/assets/textures/rust.jpg",
    proceduralType: "rock",
    swatch: "linear-gradient(135deg, #4b5563 0%, #1f2937 100%)",
    desc: "Cellular micro-crag perturbation with high roughness Oren-Nayar diffuse approximation and rock surface texture map.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "18 ALUs",
      texSamplers: "1 Albedo Map (rust.jpg)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Ultra Safe for Mobile"
    }
  },
  gold: {
    key: "gold",
    name: "Polished 24K Pure Gold",
    category: "reflective",
    icon: "👑",
    matTypeId: 0,
    bumpStrength: 0.0,
    color: [1.00, 0.78, 0.28],
    roughness: 0.12,
    metallic: 1.0,
    clearCoat: 0.10,
    noiseScale: 1.0,
    anisotropy: 0.0,
    proceduralType: "standard",
    swatch: "linear-gradient(135deg, #fbbf24 0%, #b45309 100%)",
    desc: "Cook-Torrance standard conductor BRDF with exact golden F0 spectrum.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "12 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "0.8 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Ultra Safe for Mobile",
      desc: "Standard PBR conductor math with negligible fill-rate footprint."
    }
  },
  chrome: {
    key: "chrome",
    name: "Mirror Specular Chrome",
    category: "reflective",
    icon: "🪞",
    matTypeId: 0,
    bumpStrength: 0.0,
    color: [0.95, 0.95, 0.98],
    roughness: 0.04,
    metallic: 1.0,
    clearCoat: 0.20,
    noiseScale: 1.0,
    anisotropy: 0.0,
    proceduralType: "standard",
    swatch: "linear-gradient(135deg, #e2e8f0 0%, #475569 100%)",
    desc: "Ultra-low roughness conductor BRDF with complete mirror reflection response.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "12 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "0.8 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Ultra Safe for Mobile",
      desc: "Mirror specular lobe calculation."
    }
  },
  glass: {
    key: "glass",
    name: "Refractive Crystal Glass",
    category: "reflective",
    icon: "🔮",
    matTypeId: 10,
    bumpStrength: 0.2,
    color: [0.85, 0.95, 1.00],
    roughness: 0.02,
    metallic: 0.0,
    clearCoat: 1.0,
    noiseScale: 1.0,
    anisotropy: 0.0,
    proceduralType: "glass",
    swatch: "linear-gradient(135deg, #a5f3fc 0%, #0284c7 100%)",
    desc: "Fresnel dielectric transmission with Cauchy chromatic dispersion and screen depth sampling.",
    matCost: {
      rating: "MEDIUM",
      badgeClass: "medium",
      alus: "32 ALUs",
      texSamplers: "1 Depth / Screen",
      bandwidth: "2.8 GB/s",
      fpsEstimate: "58 FPS Balanced",
      mobileVerdict: "Moderate Cost (OK for modern phones)",
      desc: "Screen-space refraction pass with Fresnel transmission math."
    }
  },
  water: {
    key: "water",
    name: "Procedural Trochoidal Ripple Water",
    category: "reflective",
    icon: "🌊",
    matTypeId: 13,
    bumpStrength: 2.8,
    color: [0.10, 0.45, 0.75],
    roughness: 0.08,
    metallic: 0.10,
    clearCoat: 0.95,
    noiseScale: 25.0,
    anisotropy: 0.20,
    proceduralType: "water",
    swatch: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    desc: "Dual harmonic trochoidal wave normal synthesis for dynamic surface ripples.",
    matCost: {
      rating: "MEDIUM",
      badgeClass: "medium",
      alus: "28 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "2.1 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile",
      desc: "Dual sine/cosine derivative normal evaluation in fragment stage."
    }
  },
  marble: {
    key: "marble",
    name: "Procedural Calacatta Marble",
    category: "procedural",
    icon: "🏛️",
    matTypeId: 4,
    bumpStrength: 0.8,
    color: [0.92, 0.92, 0.94],
    roughness: 0.28,
    metallic: 0.0,
    clearCoat: 0.85,
    noiseScale: 16.0,
    anisotropy: 0.0,
    proceduralType: "marble",
    swatch: "linear-gradient(135deg, #f8fafc 0%, #94a3b8 100%)",
    desc: "Multi-octave Perlin turbulence vein synthesis with subsurface scattering approximation.",
    matCost: {
      rating: "HIGH",
      badgeClass: "heavy",
      alus: "46 ALUs",
      texSamplers: "0 (Heavy Math)",
      bandwidth: "3.4 GB/s",
      fpsEstimate: "50 FPS (Heavy)",
      mobileVerdict: "Heavy on Low-End Mobile",
      desc: "3 octaves of analytical fractional turbulence with SSS light falloff."
    }
  },
  obsidian: {
    key: "obsidian",
    name: "Volcanic Obsidian Glass",
    category: "reflective",
    icon: "🖤",
    matTypeId: 0,
    bumpStrength: 0.1,
    color: [0.08, 0.08, 0.12],
    roughness: 0.05,
    metallic: 0.1,
    clearCoat: 0.9,
    noiseScale: 1.0,
    anisotropy: 0.0,
    proceduralType: "standard",
    swatch: "linear-gradient(135deg, #1e293b 0%, #020617 100%)",
    desc: "Deep volcanic glass with glossy clearcoat dielectric rim.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "12 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "0.8 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Ultra Safe for Mobile"
    }
  },
  velvet: {
    key: "velvet",
    name: "Deep Crimson Sheen Velvet",
    category: "special",
    icon: "🧵",
    matTypeId: 9,
    bumpStrength: 1.2,
    color: [0.55, 0.12, 0.25],
    roughness: 0.72,
    metallic: 0.0,
    clearCoat: 0.0,
    noiseScale: 1.0,
    anisotropy: 0.0,
    proceduralType: "velvet",
    swatch: "linear-gradient(135deg, #9f1239 0%, #4c0519 100%)",
    desc: "Charlie sheen BRDF with grazing rim fabric light wrapping.",
    matCost: {
      rating: "MEDIUM",
      badgeClass: "medium",
      alus: "24 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "1.8 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile",
      desc: "Inverted Fresnel rim wrap simulates micro-fibers along silhouette."
    }
  },
  carbon_fiber: {
    key: "carbon_fiber",
    name: "Twill Weave Carbon Fiber",
    category: "procedural",
    icon: "🏎️",
    matTypeId: 5,
    bumpStrength: 1.8,
    color: [0.12, 0.13, 0.15],
    roughness: 0.30,
    metallic: 0.45,
    clearCoat: 1.0,
    noiseScale: 40.0,
    anisotropy: 0.90,
    proceduralType: "carbon_fiber",
    swatch: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    desc: "Dual-angle anisotropic cross reflection under clearcoat glaze.",
    matCost: {
      rating: "MEDIUM",
      badgeClass: "medium",
      alus: "28 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "2.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile",
      desc: "Checker-pattern orthogonal tangent evaluation with clearcoat."
    }
  },
  rust: {
    key: "rust",
    name: "Corroded Iron & Rust",
    category: "procedural",
    icon: "🧱",
    matTypeId: 6,
    bumpStrength: 2.2,
    color: [0.65, 0.28, 0.16],
    roughness: 0.82,
    metallic: 0.35,
    clearCoat: 0.0,
    noiseScale: 20.0,
    anisotropy: 0.0,
    textureKey: "rust",
    textureUrl: "/assets/textures/rust.jpg",
    proceduralType: "rust",
    swatch: "linear-gradient(135deg, #b45309 0%, #451a03 100%)",
    desc: "Corroded iron oxide texture map combined with procedural noise mask blending smooth conductor and rough oxide.",
    matCost: {
      rating: "MEDIUM",
      badgeClass: "medium",
      alus: "30 ALUs",
      texSamplers: "1 Albedo Map (rust.jpg)",
      bandwidth: "2.4 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile",
      desc: "Analytical threshold mask smoothly interpolating two PBR lobes with 2D rust texture."
    }
  },
  metal: {
    key: "metal",
    name: "Brushed Aerospace Titanium",
    category: "reflective",
    icon: "⚙️",
    matTypeId: 3,
    bumpStrength: 1.4,
    color: [0.75, 0.78, 0.82],
    roughness: 0.25,
    metallic: 0.95,
    clearCoat: 0.0,
    noiseScale: 35.0,
    anisotropy: 0.60,
    textureKey: "metal1",
    textureUrl: "/assets/textures/metal/metal1.webp",
    proceduralType: "metal",
    swatch: "linear-gradient(135deg, #94a3b8 0%, #475569 100%)",
    desc: "Brushed aerospace titanium plate with 2D texture map sampler and directional anisotropic highlights.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "16 ALUs",
      texSamplers: "1 Albedo Map (metal1.webp)",
      bandwidth: "1.4 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  metal_weathered: {
    key: "metal_weathered",
    name: "Weathered Industrial Steel",
    category: "reflective",
    icon: "⛓️",
    matTypeId: 3,
    bumpStrength: 1.8,
    color: [0.70, 0.72, 0.75],
    roughness: 0.45,
    metallic: 0.90,
    clearCoat: 0.1,
    noiseScale: 25.0,
    anisotropy: 0.5,
    textureKey: "metal2",
    textureUrl: "/assets/textures/metal/metal2.webp",
    proceduralType: "metal",
    swatch: "linear-gradient(135deg, #64748b 0%, #334155 100%)",
    desc: "Weathered industrial steel plate with surface scratches and 2D texture map sampler.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "16 ALUs",
      texSamplers: "1 Albedo Map (metal2.webp)",
      bandwidth: "1.4 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  cyber_grid: {
    key: "cyber_grid",
    name: "Cyber Circuit Data Grid",
    category: "special",
    icon: "⚡",
    matTypeId: 11,
    bumpStrength: 1.0,
    color: [0.10, 0.85, 0.95],
    roughness: 0.20,
    metallic: 0.50,
    clearCoat: 0.8,
    noiseScale: 30.0,
    anisotropy: 0.0,
    textureKey: "tex01",
    textureUrl: "/assets/textures/tex01.webp",
    proceduralType: "hologram",
    swatch: "linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)",
    desc: "Cybernetic circuit grid texture with neon emissive data pathways.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "18 ALUs",
      texSamplers: "1 Albedo Map (tex01.webp)",
      bandwidth: "1.4 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  white_metal: {
    key: "white_metal",
    name: "White Alloy Composite",
    category: "reflective",
    icon: "⬜",
    matTypeId: 0,
    bumpStrength: 0.5,
    color: [0.92, 0.94, 0.98],
    roughness: 0.18,
    metallic: 0.88,
    clearCoat: 0.4,
    noiseScale: 15.0,
    anisotropy: 0.0,
    textureKey: "whiteMetal",
    textureUrl: "/assets/textures/white-metal.png",
    proceduralType: "standard",
    swatch: "linear-gradient(135deg, #f1f5f9 0%, #cbd5e1 100%)",
    desc: "Clean white composite alloy with smooth metallic reflections and texture sampler.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "14 ALUs",
      texSamplers: "1 Albedo Map (white-metal.png)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  diamond_plate: {
    key: "diamond_plate",
    name: "Diamond Tread Metal Plate",
    category: "reflective",
    icon: "🔶",
    matTypeId: 3,
    bumpStrength: 2.2,
    color: [0.85, 0.88, 0.92],
    roughness: 0.25,
    metallic: 0.95,
    clearCoat: 0.2,
    noiseScale: 20.0,
    anisotropy: 0.4,
    textureKey: "whiteMetal2",
    textureUrl: "/assets/textures/white-metal2.webp",
    proceduralType: "metal",
    swatch: "linear-gradient(135deg, #94a3b8 0%, #475569 100%)",
    desc: "Diamond tread industrial flooring metal plate texture sampler.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "16 ALUs",
      texSamplers: "1 Albedo Map (white-metal2.webp)",
      bandwidth: "1.4 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  matrix: {
    key: "matrix",
    name: "Matrix Data Stream",
    category: "special",
    icon: "💻",
    matTypeId: 11,
    bumpStrength: 0.0,
    color: [0.10, 0.95, 0.45],
    roughness: 0.10,
    metallic: 0.00,
    clearCoat: 0.0,
    noiseScale: 25.0,
    anisotropy: 0.0,
    textureKey: "matrix1",
    textureUrl: "/assets/textures/matrix1.webp",
    proceduralType: "hologram",
    swatch: "linear-gradient(135deg, #22c55e 0%, #14532d 100%)",
    desc: "Matrix digital stream texture map with cascading code rain.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "18 ALUs",
      texSamplers: "1 Albedo Map (matrix1.webp)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  red_crystal: {
    key: "red_crystal",
    name: "Crimson Energy Crystal",
    category: "special",
    icon: "🔴",
    matTypeId: 12,
    bumpStrength: 1.0,
    color: [0.95, 0.20, 0.30],
    roughness: 0.08,
    metallic: 0.10,
    clearCoat: 0.9,
    noiseScale: 15.0,
    anisotropy: 0.0,
    textureKey: "red1",
    textureUrl: "/assets/textures/red1.webp",
    proceduralType: "neon",
    swatch: "linear-gradient(135deg, #ef4444 0%, #7f1d1d 100%)",
    desc: "Crimson energy crystal texture with HDR emissive luminance.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "16 ALUs",
      texSamplers: "1 Albedo Map (red1.webp)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  xrp_emblem: {
    key: "xrp_emblem",
    name: "XRP Coin Metal Emblem",
    category: "reflective",
    icon: "🪙",
    matTypeId: 0,
    bumpStrength: 1.5,
    color: [0.20, 0.65, 0.95],
    roughness: 0.12,
    metallic: 0.95,
    clearCoat: 0.5,
    noiseScale: 10.0,
    anisotropy: 0.0,
    textureKey: "xrp",
    textureUrl: "/assets/textures/xrp.webp",
    proceduralType: "standard",
    swatch: "linear-gradient(135deg, #38bdf8 0%, #0369a1 100%)",
    desc: "Metallic XRP Coin emblem texture with polished conductor reflections.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "14 ALUs",
      texSamplers: "1 Albedo Map (xrp.webp)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  star_nebula: {
    key: "star_nebula",
    name: "Cosmic Star Nebula",
    category: "special",
    icon: "🌌",
    matTypeId: 11,
    bumpStrength: 0.0,
    color: [0.75, 0.35, 0.95],
    roughness: 0.15,
    metallic: 0.00,
    clearCoat: 0.6,
    noiseScale: 20.0,
    anisotropy: 0.0,
    textureKey: "star1",
    textureUrl: "/assets/textures/star1.png",
    proceduralType: "hologram",
    swatch: "linear-gradient(135deg, #a855f7 0%, #581c87 100%)",
    desc: "Deep space cosmic star nebula texture.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "16 ALUs",
      texSamplers: "1 Albedo Map (star1.png)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  control_panel: {
    key: "control_panel",
    name: "Control Panel Interface",
    category: "procedural",
    icon: "🎛️",
    matTypeId: 5,
    bumpStrength: 1.5,
    color: [0.45, 0.50, 0.55],
    roughness: 0.35,
    metallic: 0.70,
    clearCoat: 0.3,
    noiseScale: 18.0,
    anisotropy: 0.0,
    textureKey: "pushBtn",
    textureUrl: "/assets/textures/pushBtn.webp",
    proceduralType: "carbon_fiber",
    swatch: "linear-gradient(135deg, #64748b 0%, #1e293b 100%)",
    desc: "Industrial control panel interface button texture.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "18 ALUs",
      texSamplers: "1 Albedo Map (pushBtn.webp)",
      bandwidth: "1.4 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile"
    }
  },
  magma: {
    key: "magma",
    name: "Volcanic Magma & Lava Crust",
    category: "procedural",
    icon: "🌋",
    matTypeId: 7,
    bumpStrength: 2.0,
    color: [0.85, 0.25, 0.05],
    roughness: 0.65,
    metallic: 0.0,
    clearCoat: 0.0,
    noiseScale: 18.0,
    anisotropy: 0.0,
    proceduralType: "magma",
    swatch: "linear-gradient(135deg, #f97316 0%, #7f1d1d 100%)",
    desc: "Voronoi magma fracture cracks with animated heat glow and dark basalt crust.",
    matCost: {
      rating: "HIGH",
      badgeClass: "heavy",
      alus: "42 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "3.1 GB/s",
      fpsEstimate: "52 FPS Balanced",
      mobileVerdict: "Moderate Cost on Mobile",
      desc: "Procedural cellular fracture network with dynamic emissive pulses."
    }
  },
  car_paint: {
    key: "car_paint",
    name: "Flake Metallic Clear Coat Paint",
    category: "reflective",
    icon: "🚗",
    matTypeId: 8,
    bumpStrength: 1.0,
    color: [0.85, 0.15, 0.20],
    roughness: 0.20,
    metallic: 0.85,
    clearCoat: 1.0,
    noiseScale: 50.0,
    anisotropy: 0.0,
    proceduralType: "car_paint",
    swatch: "linear-gradient(135deg, #e11d48 0%, #881337 100%)",
    desc: "Dual-layer PBR with micro-specular sparkling flakes and dielectric top coat.",
    matCost: {
      rating: "MEDIUM",
      badgeClass: "medium",
      alus: "26 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "2.0 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile",
      desc: "Specular flake noise layer under a polished dielectric glaze."
    }
  },
  leather: {
    key: "leather",
    name: "Pebble Grain Full-Grain Leather",
    category: "procedural",
    icon: "👞",
    matTypeId: 14,
    bumpStrength: 1.9,
    color: [0.45, 0.26, 0.16],
    roughness: 0.58,
    metallic: 0.0,
    clearCoat: 0.15,
    noiseScale: 28.0,
    anisotropy: 0.1,
    proceduralType: "leather",
    swatch: "linear-gradient(135deg, #78350f 0%, #3d1a04 100%)",
    desc: "Organic cellular Voronoi pebble displacement with soft sheen response.",
    matCost: {
      rating: "MEDIUM",
      badgeClass: "medium",
      alus: "26 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "2.0 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Safe for Mobile",
      desc: "Procedural cellular pebble normal displacement with low overhead."
    }
  },
  hologram: {
    key: "hologram",
    name: "Quantum Holographic Matrix",
    category: "special",
    icon: "🌐",
    matTypeId: 11,
    bumpStrength: 0.0,
    color: [0.10, 0.90, 0.85],
    roughness: 0.10,
    metallic: 0.0,
    clearCoat: 0.0,
    noiseScale: 25.0,
    anisotropy: 0.0,
    proceduralType: "hologram",
    swatch: "linear-gradient(135deg, #06b6d4 0%, #0284c7 100%)",
    desc: "Fresnel rim glow with animated scanline interference.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "18 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "1.2 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Ultra Safe for Mobile",
      desc: "Fast time-modulated trigonometric scanlines and Fresnel glow."
    }
  },
  neon: {
    key: "neon",
    name: "Supercharged Emissive Neon",
    category: "special",
    icon: "⚡",
    matTypeId: 12,
    bumpStrength: 0.0,
    color: [0.95, 0.20, 0.80],
    roughness: 0.05,
    metallic: 0.0,
    clearCoat: 0.0,
    noiseScale: 1.0,
    anisotropy: 0.0,
    proceduralType: "neon",
    swatch: "linear-gradient(135deg, #ec4899 0%, #be185d 100%)",
    desc: "HDR emissive luminance with smooth gaussian bloom falloff.",
    matCost: {
      rating: "LOW",
      badgeClass: "safe",
      alus: "14 ALUs",
      texSamplers: "0 (Pure Math)",
      bandwidth: "1.0 GB/s",
      fpsEstimate: "60 FPS Solid",
      mobileVerdict: "Ultra Safe for Mobile",
      desc: "Direct HDR additive color emission with minimal fragment overhead."
    }
  }
};
